### ISSUE TITLE
Create More Powerful Upgrades

### ISSUE THREAD

**Issue by lrobt97** [lrobt97/Control-Theory#2]
After an initial gametest it seems like the milestones and upgrades as stands aren't "powerful" enough. This means that it is difficult to make much progress. 

A redesign of the main equation/variables/milestone upgrades would fix this issue.

**Comment by Skyhigh173** [comment]
ya
but there is a major bug , just like what i say in discord

**Comment by lrobt97** [comment]
> ya but there is a major bug , just like what i say in discord

This will be resolved in a more formal release once this line is uncommented (210):
`  if (T > getTmax(Tmax.level)) {
    //resetStage();
  }
`
